function [ensembleAvg,ensembleVar] = ensembleAverageWithIndex(inputData, index)
arguments
  inputData = ones(1001,1) % Column Array
  index = 1:5:1001
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  % ensembleAverageWithIndex Calculate the ensembled average
  %   
  % Inputs:
  %   inputData = array of data to process
  %   index = array of indexes of time steps desired to take averages from; generated by getdatetimeIndex.m
  %
  % Outputs:
  %   ensembleAvg = array of ensembled average of inputData
  %   ensembleVar = array of ensembled variance of inputData
  %
  % Created by Tyler Knapp 09/30/2025
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                           % Function Start %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  % Pre-allocate arrays
  ensembleAvg = NaN(length(index)-1,1);
  ensembleVar = NaN(length(index)-1,1);
  % Loop through time series
  for i = 1:length(index)-1
    if isnan(index(i+1))
      break
    end
    ensembleAvg(i) = mean(inputData(index(i):index(i+1)),'omitnan');
    ensembleVar(i) = var(inputData(index(i):index(i+1)),'omitnan');
  end
end

